name: ws_action
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  cbor: ^2.0.5
  rx_command: "^4.3.2+1"

dev_dependencies:
  test:
  maybe: ^0.4.0